### ISSUE TITLE
Channel crashes when DB have item with unknown id.

### ISSUE THREAD

**Issue by Tachiorz** [aura-project/melia#29]
```
[Error] - Error while handling packet '0BB9', CZ_CONNECT.
[Exception] - System.NullReferenceException: No item data found for '628130'.
   at Melia.Channel.World.Item.LoadData() in x:\Research\TOS\melia\src\ChannelServer\World\Item.cs:line 83
   at Melia.Channel.World.Item..ctor(Int32 itemId, Int32 amount) in x:\Research\TOS\melia\src\ChannelServer\World\Item.cs:line 66
   at Melia.Channel.Database.ChannelDb.LoadCharacterItems(Character character) in x:\Research\TOS\melia\src\ChannelServer\Database\ChannelDb.cs:line 192
   at Melia.Channel.Database.ChannelDb.GetCharacter(Int64 accountId, Int64 characterId) in x:\Research\TOS\melia\src\ChannelServer\Database\ChannelDb.cs:line 122
   at Melia.Channel.Network.ChannelPacketHandler.CZ_CONNECT(ChannelConnection conn, Packet packet) in x:\Research\TOS\melia\src\ChannelServer\Network\ChannelPacketHandler.cs:line 62
   at Melia.Shared.Network.PacketHandler`1.Handle(TConnection conn, Packet packet) in x:\Research\TOS\melia\src\Shared\Network\PacketHandler.cs:line 69
   at Melia.Channel.Network.ChannelConnection.HandlePacket(Packet packet) in x:\Research\TOS\melia\src\ChannelServer\Network\ChannelConnection.cs:line 40
   at Melia.Shared.Network.Connection.OnReceive(IAsyncResult result) in x:\Research\TOS\melia\src\Shared\Network\Connection.cs:line 198
```

**Comment by exectails** [comment]
Did it actually *crash* the channel, as in closing the window? Looks like the exception was caught, so that shouldn't be the case.
